### ISSUE TITLE
RAW output should enabled UBX_RXM_SFRBX too

### ISSUE THREAD

**Issue by Stefal** [sparkfun/SparkFun_RTK_Surveyor#11]
Hi,
If you want to post process F9P data with tools like RTKLIB, you usually need ubx_rxm_rawx AND ubx_rxm_sfrbx.
I think that enabling rawx on the surveyor should enabled sfrbx too.

**Comment by nseidle** [comment]
Can be done. I'll make it an optional sentence to enable/disable by itself.

**Comment by nseidle** [comment]
Added to release candidate. Please have a go and let me know if it's what you're looking for.

**Comment by Stefal** [comment]
Thanks, I'll try ASAP

**Comment by nseidle** [comment]
Add to v1.2.

**Comment by drf5n** [comment]
> 
Added to release candidate. Please have a go and let me know if it's what you're looking for.



I see :  https://github.com/sparkfun/SparkFun_RTK_Firmware/commit/403b67150d210ba2d02a5f7ca88288781f9cd411
