### ISSUE TITLE
FR Enable other message

### ISSUE THREAD

**Issue by Stefal** [sparkfun/SparkFun_RTK_Surveyor#18]
### Subject of the issue
Feature request: Add a way to enable UBX messages not listed in the RTK Surveyor menu

I see 2 methods to do this:
- Add a very big list with all the available ubx messages
- Add a way to let the user input the message he needs

**Comment by pyrog** [comment]
> I see 2 methods to do this:

I see a third : read UBX messages from SFE_Surveyor_Settings.txt

To simplify the code,  this setting could be a CSV with decimal or hexadecimal values.

Examples:

- `log.ubx=5,19,20` enable logging of **UBX_NAV_ATT**, **UBX_NAV_HPPOSECEF** and **UBX_NAV_HPPOSLLH** messages.
- `log.ubx=0x05,0x14,0x0A` enable **UBX_NAV_ATT**, **UBX_RXM_MEASX** and **UBX_NMEA_DTM**.

See [Firmware/RTK_Surveyor/nvm.ino#L222-L375](https://github.com/sparkfun/SparkFun_RTK_Surveyor/blob/613c84276a596a0068502d3ba7729610841dcfa2/Firmware/RTK_Surveyor/nvm.ino#L222-L375)

PS: `str2d` accept hex values too 😀
See http://tpcg.io/88sNLTi4

**Comment by nseidle** [comment]
str2d = I did not know that! Thanks!

I'm not convinced enter HEX values is the ideal user experience. While it's a bit of work to get all the menus setup, I think it's better than requiring the user to identify that 0x0A is the NMEA_DTM message.

**Comment by pyrog** [comment]
> str2d = I did not know that! 

Me too 😅

> I'm not convinced enter HEX values is the ideal user experience.

I agree 😀
Usually hex values came from [ZED-F9P Interface Description](https://www.u-blox.com/en/docs/UBX-18010854) so it's error proof for experienced user to cut and past it in the Settings file.

**Comment by Stefal** [comment]
In the meantime, is there a way to log other UBX messages? I have enabled some with U-Center, but I don't see them inside the ubx file stored on the sd card.

**Comment by nseidle** [comment]
Unfortunately I don't have an interim solution. I'll try to get a new firmware out this week for your testing.

**Comment by nseidle** [comment]
Hi Stefal - sorry for the delay. I think I've got it button up. [RTK_Surveyor_Firmware_v13RC_May25.zip](https://github.com/sparkfun/SparkFun_RTK_Surveyor/files/6542604/RTK_Surveyor_Firmware_v13RC_May25.zip) has piles of improvements (I really need to get to a release) including individual rate selection for 

* NMEA - 13
* NAV - 24
* RXM - 5
* MON - 10
* TIM - 3
* RTCM - 12

67 messages. Please give this a try and let me know what you think. I would like to freeze this RC and release early next week.

The main menu has a message sub menu, that then has sub menus for each group:

![image](https://user-images.githubusercontent.com/117102/119574740-2a177080-bd73-11eb-8d06-3f83563973a5.png)

Additionally, Bluetooth SPP now passes incoming traffic out to the ZED. So over Bluetooth, you can configure the ZED-F9P in any fashion using u-center. Note, however, that I haven't yet implemented a setting scanner so if the setting is part of the settings maintained by the ESP32, the ESP32 will overwrite the ZED setting at the next power up.

Please keep an eye out for typos in the menus and settings. I'm sure I messed up a few things.

**Comment by pyrog** [comment]
I can't load the firmware :disappointed: 
I use Ubuntu so I didn't used [SD Memory Card Formatter](https://www.sdcard.org/downloads/formatter/)

```
SparkFun RTK Surveyor v1.1
** Bluetooth broadcasting as: Surveyor Rover-0CE2 **
Menu: Update Firmware Menu
1) Load RTK_Surveyor_Firmware_v13RC_May25.bin
x) Exit
1Do you have line endings turned on?
Loading RTK_Surveyor_Firmware_v13RC_May25.bin
Moving file to OTA sectionBytes to write: 1513328
[=0%E (55260) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (55260) task_wdt:  - IDLE0 (CPU 0)
E (55260) task_wdt: Tasks currently running:
E (55260) task_wdt: CPU 0: F9Read
E (55260) task_wdt: CPU 1: loopTask
E (55260) task_wdt: Aborting.
abort() was called at PC 0x400e2e13 on core 0

Backtrace: 0x40092704:0x3ffbe320 0x40092935:0x3ffbe340 0x400e2e13:0x3ffbe360 0x40084f75:0x3ffbe380 0x400df7f1:0x3ffeb2b0 0x400d6c56:0x3ffeb2d0 0x400d8de9:0x3ffeb2f0 0x400d889c:0x3ffeb310 0x400d88da:0x3ffeb330 0x400d8b21:0x3ffeb360 0x400d8c80:0x3ffeb380 0x400d84ad:0x3ffeb3a0 0x400d6e9e:0x3ffeb3c0 0x400d7385:0x3ffeb3e0 0x400d6542:0x3ffeb410 0x4008ee19:0x3ffeb430

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1216
ho 0 tail 12 room 4
load:0x40078000,len:9720
ho 0 tail 12 room 4
load:0x40080400,len:6352
entry 0x400806b8
microSD online
MAX17048 configuration complete
Batt (100%): Voltage: 4.19V Discharging: -0.21%/hr Green all good
Bluetooth broadcasting as: Surveyor Rover-0CE2
GNSS configuration complete
Rover Accuracy (m): 11.3690 No LEDs
Log file created: SFE_Surveyor_210526_120013.txt
```

**Comment by nseidle** [comment]
Hi Pyrog - I just pushed the combined binary. Please use [esptool instructions](https://github.com/sparkfun/SparkFun_RTK_Surveyor/tree/master/Binaries) to load.

[RTK_Surveyor_Firmware_v13RC_May25_combined.zip](https://github.com/sparkfun/SparkFun_RTK_Surveyor/files/6547793/RTK_Surveyor_Firmware_v13RC_May25_combined.zip)

**Comment by nseidle** [comment]
I was able to nail down the panic to the F9Read task. It's now disabled along with any WiFi that is turned on. New RC: [RTK_Surveyor_Firmware_v13RC_May26_combined.zip](https://github.com/sparkfun/SparkFun_RTK_Surveyor/files/6549314/RTK_Surveyor_Firmware_v13RC_May26_combined.zip)

**Comment by pyrog** [comment]
With **firmware v13RC May26** the microSD content is not displayed:

```
Menu: Test Menu
Bluetooth broadcasting as: Surveyor Rover-0CE2
Radio Port is now outputting RTCM
microSD card detected: Failed to create test file. Format SD card with 'SD Card Formatter'.
Qwiic port failed! No display detected.
Any character received over Blueooth connection will be displayed here
1) Display microSD contents
2) Scan for Qwiic OLED display
x) Exit
Files found (date time size name):




```

Should be:
```
RTK_Surveyor_Firmware_v13RC_May25.bin
SFE_Surveyor_210526_132837.txt
SFE_Surveyor_210527_063019.txt
SFE_Surveyor_Settings.txt
SFE_Surveyor_210526_132759.txt
SFE_Surveyor_210527_061118.txt
SFE_Surveyor_210527_063257.ubx
System Volume Information

```

**Comment by Stefal** [comment]
> Hi Stefal - sorry for the delay. I think I've got it button up. 

Hi!
Thanks !
I don't have much time now, but I did a quick test, and it works! I have a lot of checksum errors in the ubx file...perhaps I pushed the rate too high (10Hz). I'll make another test tomorrow at 5hz.

some remarks:
I don't see the option to enable/stop logging anymore.

> Additionally, Bluetooth SPP now passes incoming traffic out to the ZED. So over Bluetooth, you can configure the ZED-F9P in any fashion using u-center. Note, however, that I haven't yet implemented a setting scanner so if the setting is part of the settings maintained by the ESP32, the ESP32 will overwrite the ZED setting at the next power up.

Nice !

> Please keep an eye out for typos in the menus and settings. I'm sure I messed up a few things.

Didn't see anyone but I didn't look close.

**Comment by pyrog** [comment]
Some remarks:
- Setting the logging is a bit tedious.
- Adding an option to enable/disable data logging could useful.<br/>The alternative is to simply insert/remove the microSD card ? :thinking: 
- Move the "Display microSD contents" to the main menu ?
- The RTK Surveyor need to be rebooted to load/display the SD card content.

**Comment by Stefal** [comment]
At 5Hz, I still have many checksum errors in my ubx file. I will try tomorrow with another sd card.

One other question, when I connect the RTK surveyor to my smartphone, and send a ntrip correction (lefebure ntrip client), I see this in my terminal:
```
[I][BluetoothSerial.cpp:254] esp_spp_cb(): ESP_SPP_SRV_OPEN_EVT: 0
Client Connected
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 478 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 200 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 245 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 302 bytes
Batt (43%): Voltage: 4.01V Charging: 15.81%/hr Yellow
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 478 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 302 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 478 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 302 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 278 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 293 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 225 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 302 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 245 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 4 bytes
Batt (43%): Voltage: 4.01V Charging: 15.81%/hr Yellow
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 165 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 246 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 302 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 307 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 402 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 244 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 290 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 361 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 70 bytes
[E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 136 bytes
Batt (43%): Voltage: 4.01V Charging: 15.81%/hr Yellow
```
Do I have to worry ?

**Comment by nseidle** [comment]
@pyrog - Good feedback. Thank you.

> Setting the logging is a bit tedious.

I can't think of a better way to do it :)

> Adding an option to enable/disable data logging could useful.

(Head smack) Yep. I've re-added it. Thanks for pointing that out.

> Move the "Display microSD contents" to the main menu ?

Done.

**Comment by nseidle** [comment]
@Stefal - I doubt it is your SD card. Most times my SD card either works or fails at the start. I suspect it is something wrong with the code. How are you viewing/detecting the checksum errors?

My fault. I failed to turn off the ESP32 debug messages. I'll be sure to set it to 'None' in the next RC.

![image](https://user-images.githubusercontent.com/117102/120006881-93c39480-bf96-11eb-8397-adc403dda1d1.png)

**Comment by Stefal** [comment]
> 
> 
> @Stefal - How are you viewing/detecting the checksum errors?
I have 3 methods:
- My very [dirty script](https://github.com/Stefal/ubx-to-gpx) to convert ubx file to .pos file. With my last ubx log, I can't convert the entire file, it crash before the end of the log.
- Open the ubx file in U-center, and export it to a kml file, open this kml in [Josm](https://josm.openstreetmap.de/) and check if there are some holes in the trace 
![image](https://user-images.githubusercontent.com/8255984/120009550-600b5d80-bfdc-11eb-9738-ecf2a06df09a.png)

- I can playback an ubx file with [pyGpsClient](https://github.com/semuconsulting/PyGPSClient) and look at the errors in the terminal.

**Comment by nseidle** [comment]
@stefal - Awesome. Thanks! I think I found the [source of the corruption](https://github.com/sparkfun/SparkFun_RTK_Surveyor/commit/201183f686a2bc2ac1f1eb3509c1c1dd05318f5d).

**Comment by nseidle** [comment]
@Stefal - We're mixing many issues together here, so let's try to open some new ones. Your report of the 

> [E][BluetoothSerial.cpp:316] esp_spp_cb(): RX Full! Discarding 136 bytes

Is very interesting and a little disconcerting. I'm moving that to its [own issue](https://github.com/sparkfun/SparkFun_RTK_Surveyor/issues/23).

**Comment by nseidle** [comment]
Hi @Stefal and @pyrog - I think I've got this and all the smaller issues above fixed. Thanks for much for your help testing this. Please checkout the [latest release](https://github.com/sparkfun/SparkFun_RTK_Surveyor/releases/tag/v1.3) and open new issues as they come up.
