### ISSUE TITLE
RTK Surveor does not charge Lipo battery

### ISSUE THREAD

**Issue by artosaurus** [sparkfun/SparkFun_RTK_Surveyor#2]
### RTK Surveor does not charge Lipo battery

RTK Surveyor does not charge its Lipo battery when connected to USB with wall adapter. The LED is totally off. When I switch power on the LED is red. I replaced new Lipo-battery and this does not help. It is possible to charge he battery of Surveyor using Turnigy charger so the battery is not malfunctioning. 
To your information, I have RTK Surveyor and also RTK Express. I am using Surveoyr as Base and Express as Rover.
I bought Surveyor about a year ago and did not use it at all because I noticed that I need a second unit. Therefore, I bought RTK express during summer 2021 and now I started to use these together and noticed this battery cahrger problem in Surveyor.  
I tested Surveyor using the battery from RTK Express but the same problem exist - the LED is off and does not charge the battery. My RTK Surveyor is damaged for some reason. I can use it only when it is connected to an external USB power bank.

### Your workbench
SparkFun RTK Surveyor v1.3-Jun  7 2021.
Bluetooth is working OK.
NTRIP is coming via radio or alternatively website RT2GO and Bluetooth. 
Everything is powered by external USB because battery is empty. Surveyour does not charge the battery anymore. The LED is totally off when main power of Surveyor is off and USB is connected.

### Steps to reproduce
Tell us how to reproduce this issue. Please include a copy of your settings.txt file used on the unit.
[SFE_Surveyor_Settings.txt](https://github.com/sparkfun/SparkFun_RTK_Surveyor/files/6872461/SFE_Surveyor_Settings.txt)

### Expected behavior
LED should be blue and battery should charge

### Actual behavior
LED is off and battery does not charge.

**Comment by nseidle** [comment]
Ah! Sorry for letting this sit for so many days. My apologies.

I believe we've got a return in the works for you. Correct me if not.

We found a jumper on the charge IC that was causing it to fail. We're working on updating the test procedure to catch this fault in the future.

I'm going to leave open until we confirm you're charging again.

**Comment by artosaurus** [comment]
Thank you for the response. 
It is not charging.

So what should I do now? Can I fix this myself? Could you identify the
jumper so I can fix it if it is possible?

**Comment by nseidle** [comment]
Please contact me nathan at sparkfun and I'll get you connected with the right support folks. I don't recommend you attempt to fix it unless you are proficient at hot-air rework. We'll remove the IC, clean up the solder joints and re-mount the charger IC.

![image](https://user-images.githubusercontent.com/117102/128074364-5af3d5b6-c932-40b2-8db4-ce9ba24306d7.png)
