### ISSUE TITLE
Enable/Disable message group logging

### ISSUE THREAD

**Issue by Stefal** [sparkfun/SparkFun_RTK_Surveyor#24]
### Subject of the issue
With the latest RC, if I want to enable/disable ubx messages or nmea messages logging, I have to change each message value to 0/1. It's a long process. And when I need to enable back Nmea, I don't remember the default settings, so I end up with a complete reset.

### Your workbench
* What version of RTK Surveyor firmware are you running? 
13RC_May28

### Expected behavior
Inside logging menu we could have a on/off setting for nmea and ubx, like the previous releases

**Comment by pyrog** [comment]
> It's a long process.

That's what I mean in in https://github.com/sparkfun/SparkFun_RTK_Surveyor/issues/18#issuecomment-850216333_
- Setting the logging is a bit tedious.

**Comment by nseidle** [comment]
Let's see so a menu item that was something like:

* "Set to Surveying defaults" - clears all msg, enables the 5 NMEA messages GGA, GSA, GST, GSV, and RMC
* "Set to PPP Logging defaults" - clears all msg, enables the 5 NMEA messages GGA, GSA, GST, GSV, and RMC, as well as RAWX and SFRBX

How does that sound?

**Comment by pyrog** [comment]
> How does that sound?
Sound good :smiley: 

I have a suggestion for the Surveyor that is also usable for the [RTK Express](https://www.sparkfun.com/products/18019)...
Have a user editable list of settings and for the RTK Surveyor:
Select 1 setting of the list for the base mode, and another 1 setting for the rover mode.

For the RTK Express, select 1 of the settings of the list.

Examples:
- "SW maps hiking" (NMEA at 1 Hz + DYN_MODEL_PEDESTRIAN)
- "SW maps car" (NMEA  at 4 Hz + DYN_MODEL_AUTOMOTIVE)
- "Lefebure biking" (UBX  at 2 Hz + DYN_MODEL_BIKE)
- "Drone" (UBX at 10 Hz + DYN_MODEL_AIRBORNE1g)

One could set the Surveyor with _"SW maps car"_  in Rover Setup, and  _"SW maps hiking"_ in Base Setup.

**Comment by nseidle** [comment]
@pyrog - Oh how the features creep ;) What you're asking for is effectively multiple configuration files and being able to select between them. Ok, maybe. But let's move that to a new issue if you want to.

@Stefal - I've added the ability to reset to two defaults as well as all off, and all messages on (useful for my testing).

![image](https://user-images.githubusercontent.com/117102/121087713-048e5c00-c7a2-11eb-93d8-0eafacf954bc.png)

This will be in next RC.
