### ISSUE TITLE
100 cm led is off in RTK

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Surveyor#27]
### Subject of the issue
100 cm led is off.

### Your workbench
* v13RC May 28.

### Actual behavior
Note: This led is on during the autotest during startup.

![20210529_152018](https://user-images.githubusercontent.com/2158081/120158429-6aa03f80-c1f4-11eb-896b-6330d1b40ed8.jpg) ![20210529_151957](https://user-images.githubusercontent.com/2158081/120158442-6d029980-c1f4-11eb-9a27-e404de7dfb98.jpg)

**Comment by pyrog** [comment]
I opened the case and leave a cable between the led and the light pipe.
![image](https://user-images.githubusercontent.com/2158081/120184301-1a83a600-c211-11eb-8810-65d8488d4196.png)

**Comment by nseidle** [comment]
Thank you for documenting! Yes, we see this during production as well. If the cables are not routed correctly they can sometimes fall between the LED on the PCB and the lightpipe causing the outside lights to look dim or off. Moving the internal cables should fix the issue.
