### ISSUE TITLE
Add dynamic model setting

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Surveyor#29]
### Subject of the feature request
Add an option in the settings to set the dynamic model for the rover mode.

See:
- [SparkFun_Ublox_Arduino_Library/keywords.txt](https://github.com/sparkfun/SparkFun_Ublox_Arduino_Library/blob/1e70755453a898d8267ced641500c33d377409b7/keywords.txt#L258-L267)
- 3.1.7.1 Platform settings in [ZED-F9P — Integration manual](https://www.u-blox.com/sites/default/files/ZED-F9P_IntegrationManual_%28UBX-18010802%29.pdf)

**Comment by nseidle** [comment]
A fine idea. I'll implement in v1.4.

**Comment by nseidle** [comment]
Added to v1.4RC. Please test and let me know what you think.

**Comment by pyrog** [comment]
I have done a quick test with the Automotive model.
My impression was that the device lost less the RTK fix.

Drawing the track seem to show that:
<img width=33% src="https://user-images.githubusercontent.com/2158081/122426756-cad30780-cf90-11eb-9c83-0125b3b5812f.jpg"> <img width=33% src="https://user-images.githubusercontent.com/2158081/122426790-d3c3d900-cf90-11eb-83bb-c8abf043c178.jpg">
Left **default** model. Right **automotive** model
