### ISSUE TITLE
How to trigger a digital camera?

### ISSUE THREAD

**Issue by pyrog** [sparkfun/SparkFun_RTK_Surveyor#32]
Hi Nathan,

I would like trigger a DSLR camera with the PPS signal of the F9P/RTK Surveyor.

Is it possible to connect i.e. an optocoupler directly to a GPIO pin on the Data, Radio or Qwiic connector?
i.e the [SparkFun Opto-isolator Breakout](https://www.sparkfun.com/products/9118).

Or to a I2C board connected to the Qwiic connector?

**Comment by nseidle** [comment]
It's possible. The PPS signal can be routed by setting the "NMEA/Serial" switch on the back of the board to PPS/Reset. The opto-isolator is a great idea.

The RTK Express is very much designed for this. The internal Mux allows us to use either PPS or a GPIO from the ESP32 via software (no mechanical switch).

The Qwiic connector is a novel idea but is probably overkill. A [Qwiic GPIO](https://www.sparkfun.com/products/17047) would do it but be pretty bulky.
